[package]
name = "check_versions"
version = "0.0.0"
authors = ["Brett Etter <buzzec@buzzec.net>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
toml = "0.5.9"
structopt = "0.3.26"
tokio = { version = "1.17.0", features = ["full"] }
crates_io_api = "0.8.0"
