[package]
name = "easy_proc_common"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.84"
proc-macro-error = "1.0.4"
