name: Programs-Cryptid-Signer
on:
  push:
  pull_request:
jobs:
  fmt-check:
    name: Format cruiser on Rust ${{ matrix.rust }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [ 'nightly-2022-03-22' ]
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Cache make
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/cargo-make
          key: cargo-make

      - name: Install Make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-make

      - name: Run fmt
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: check_fmt

  check-escrow-example:
    name: Check escrow_example on Rust ${{ matrix.rust }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [ 'nightly-2022-03-22' ]
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Cache make
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/cargo-make
          key: cargo-make

      - name: Install Make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-make

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: cargo-check-escrow-example-${{ hashFiles('Cargo.lock') }}

      - name: Run check_escrow_example
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: check_escrow_example

  check-cruiser:
    name: Check cruiser on Rust ${{ matrix.rust }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [ 'nightly-2022-03-22' ]
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Cache make
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/cargo-make
          key: cargo-make

      - name: Install Make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-make

      - name: Run check_cruiser
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: check_cruiser

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: cargo-check-cruiser-${{ hashFiles('Cargo.lock') }}

  doc:
    name: Check docs on Rust ${{ matrix.rust }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [ 'nightly-2022-03-22' ]
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Cache make
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/cargo-make
          key: cargo-make

      - name: Install Make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-make

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: cargo-doc-${{ hashFiles('Cargo.lock') }}

      - name: Run doc
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: doc

  test-all:
    name: Test everything on Solana ${{ matrix.solana }}, Rust ${{ matrix.rust }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [ 'nightly-2022-03-22' ]
        solana: ['1.9.15', '1.9.14', '1.9.13', '1.9.12']
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Cache Solana version
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache
          key: solana-${{ matrix.solana }}

      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/${{ matrix.solana }}/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Cache make
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/cargo-make
          key: cargo-make

      - name: Install Make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-make

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: cargo-test-all-${{ hashFiles('Cargo.lock') }}

      - name: Run test_all
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: test_all
