[package]
name = "escrow_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cruiser = { path = "..", features = ["spl-token"] }
borsh = "0.9.3"
spl-token = "3.3.0"

[lib]
crate-type = ["cdylib", "lib"]
